ci(generate-assets): print the second build step output
Flutter compilation errors were hidden in the generate-assets action, which would cause the workflow to fail without printing error logs

diff --git a/.github/actions/generate-assets/action.yml b/.github/actions/generate-assets/action.yml
--- a/.github/actions/generate-assets/action.yml
+++ b/.github/actions/generate-assets/action.yml
@@ -62,27 +62,25 @@ runs:
           echo "Some Trello inputs are missing or empty, skipping all Trello parameters"
         fi
 
-        echo "Build command with environment variables:"
-        echo "$BUILD_CMD"
-
         # Run flutter build once to download coin icons and config files. 
         # This step is expected to "fail", since flutter build has to run again 
         # after the assets are downloaded to register them in AssetManifest.bin
+        echo ""
         flutter pub get > /dev/null 2>&1 || true
         $BUILD_CMD > /dev/null 2>&1 || true
         rm -rf build/*
 
-        # Run flutter build and capture its output and exit status
-        # Allow error messages from `flutter pub get` to be printed for debugging
-        # in case there are legitimate, unexpected errors.
-        flutter pub get > /dev/null
-        output=$($BUILD_CMD 2>&1)
+        # Run flutter build and capture its output
+        flutter pub get
+        echo "Running build command: $BUILD_CMD"
+        set +e  # Don't exit immediately on error
+        $BUILD_CMD
         exit_status=$?
-
+        set -e  # Restore exit on error behavior
+        
         # Check if the exit status is non-zero (indicating an error)
         if [ $exit_status -ne 0 ]; then
-            echo "Flutter build exited with status $exit_status. Output:"
-            echo "$output"
+            echo "Flutter build exited with status $exit_status"
             exit $exit_status
         fi
         echo "Done fetching packages and generating assets"
